### ISSUE TITLE
Missing information on semaphore passwd

### ISSUE THREAD

**Issue by ZenKyma** [mother-of-all-self-hosting/ansible-role-semaphore#1]
I was going to give semaphore a try, knowing little about it. But following the basic setup guide, the installation fails with:
```
TASK [galaxy/semaphore : Ensure semaphore passwd is created] *******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [synkosmos.org]: FAILED! => changed=false
  msg: |-
    Could not find or access '/srv/mash-playbook/roles/galaxy/semaphore/templates/passwd.j2' on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
```
 
The playbook neither provides `semaphore/templates/passwd.j2` nor information on how to configure it, docs don't mention it either.
Is it just copying `/etc/passwd` over to `semaphore/templates/passwd.j2` or else how do I set it up?

vars.yml:
```yml
semaphore_enabled: true
semaphore_hostname: *hidden*
# Despite the confusing naming, semaphore_admin_name needs to hold a username, not a name!
semaphore_admin_name: *hidden*
semaphore_admin_email: *hidden*
# You can generate a strong password with a command like: `pwgen -s 64 1`
semaphore_admin_password: *hidden*

# Key for encrypting access keys in database.
# It must be generated by using the following command: head -c32 /dev/urandom | base64
semaphore_access_key_encryption: *hidden*
```
